"""Configuration module for Mamut"""
from config.settings import Settings
from config.thresholds import (
    TRASH_FILTER_THRESHOLDS,
    CREATOR_RISK_THRESHOLDS,
    AUTHORITY_RISK_THRESHOLDS,
    CONCENTRATION_THRESHOLDS,
    FLOW_ANALYSIS_THRESHOLDS,
    HOLDER_QUALITY_THRESHOLDS,
    SCORING_THRESHOLDS,
    DECISION_THRESHOLDS,
    RAYDIUM_THRESHOLDS,
    SIGNAL_THRESHOLDS,
    MARKET_CONFIRMATION_THRESHOLDS,
)

__all__ = [
    "Settings",
    "TRASH_FILTER_THRESHOLDS",
    "CREATOR_RISK_THRESHOLDS",
    "AUTHORITY_RISK_THRESHOLDS",
    "CONCENTRATION_THRESHOLDS",
    "FLOW_ANALYSIS_THRESHOLDS",
    "HOLDER_QUALITY_THRESHOLDS",
    "SCORING_THRESHOLDS",
    "DECISION_THRESHOLDS",
    "RAYDIUM_THRESHOLDS",
    "SIGNAL_THRESHOLDS",
    "MARKET_CONFIRMATION_THRESHOLDS",
]